FROM golang:1.25 AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o blogservice .

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=build /app/blogservice .
EXPOSE 8082
ENV PORT=8082
ENTRYPOINT ["./blogservice"]