spring.application.name=Stakeholders

server.port=8081
logging.level.org.springframework.core.env=DEBUG

spring.mongodb.uri=mongodb+srv://kornelijekiso:mongo123@cluster0.wsvecli.mongodb.net/stakeholders?retryWrites=true&w=majority&appName=Cluster0

jwt.secret=THIS_IS_A_DEMO_SECRET_KEY_FOR_SOA_PROJECT_I_WILL_MAYBE_CHANGE_LATER
jwt.expiration=86400000