spring.application.name=GatewayService
server.port=8080
jwt.secret=${JWT_SECRET}
gateway.stakeholders-url=${STAKEHOLDERS_URL:http://localhost:8081}
gateway.blogs-url=${BLOGS_URL:http://localhost:8082}
gateway.tours-url=${TOURS_URL:http://localhost:5281}
gateway.frontend-origin=${FRONTEND_ORIGIN:http://localhost:5173}
